EquipManage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from managements import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managements.urls')),
    path('equipment/', include('equipments.urls')),
    path('student/', include('students.urls')),
    path('users/', include('users.urls')),
    path('graphs/', include('graphs.urls')),
    path('receivecode.html/', views.receivecode, name='receivecode'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path, include
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.student_register, name='student_register'),
    path('list/', views.student_list, name='student_list'),
    path('list/list_search/', views.list_search, name='list_search'),
    path('list/student_excel_download/', views.student_excel_download, name='student_excel_download'),
    path('student_check/', views.student_overlap_check, name='student_overlap_check'),
    path('detail/<int:pk>/',views.student_detail, name='student_detail'),
    path('remove/<int:pk>/',views.student_remove, name='student_remove'),
    path('student_excel_register/', views.student_excel_register, name='student_excel_register'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns=[
    path('', views.staff_login, name="staff_login"), 
    path('users/login_check', views.login_success_check, name="login_success_check"), 
    path('logout/', views.staff_logout, name="staff_logout"), 
]

students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):

    STATUS_CHOICES = (
        ('재학', '재학'),
        ('휴학', '휴학'),
        ('졸업', '졸업'),
        ('자퇴', '자퇴'),
    )

    student_id = models.CharField(max_length=7, unique=True)
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    status = models.CharField(max_length=5, choices=STATUS_CHOICES, default='재학')

    def __str__(self):
        return self.student_id

students/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student
from .forms import StudentForm
from django.contrib import messages
import json
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django import forms
from django.core.validators import FileExtensionValidator
from django.db import IntegrityError
import xlwt

@login_required(login_url='/users/')
def student_register(request):
    if request.method == 'POST':
        student_form = StudentForm(request.POST)
        if student_form.is_valid():
            student_info = student_form.save(commit=False)
            student_info.save()
            return redirect('students:student_list')
        else :
            return redirect('students:student_register')

        return render(request, 'students/student_register.html')
    else:
        student_form = StudentForm()
        return render(request, 'students/student_register.html', {'student_form':student_form})

# 학생 일괄 등록 폼
class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]) #xlsx와 xls 확장자만 허용

#학생 일괄 등록 excel view 
@login_required(login_url='/users/')
def student_excel_register(request):
    # 파일 업로드 시
    if request.method == "POST":
        try:
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                request.FILES['file'].save_to_database(
                    name_columns_by_row=0, # 첫 번째 행은 db에 저장 X 
                    model=Student, #저장 타겟이 되는 학생 모델
                    mapdict=['student_id', 'name', 'phone_number', 'email']) #엑셀에 있는 열의 값을 이 순서대로 모델에 저장
                return redirect('students:student_list')
            #업로드 파일의 문제가 있는 경우
            else:
                return redirect('students:student_excel_register')
        #db에 있는 학생이 엑셀에 있는경우 예외처리  
        except IntegrityError:
            return redirect('students:student_excel_register')
    else:
        form = UploadFileForm()
    return render(request, 'students/student_excel_register.html', {'form': form})

# 학생 리스트 엑셀 export
@login_required(login_url='/users/')
def student_excel_download(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="students.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Students')
    row_num = 0 # sheet header
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    
    columns = ['학번', '이름', '연락처', '이메일', '학적상태']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    
    rows = Student.objects.all().values_list('student_id', 'name', 'phone_number', 'email', 'status')
    for row in rows :
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    
    wb.save(response)
    return response

# 학생 번호 중복 확인
@login_required(login_url='/users/')
def student_overlap_check(request):
    student_id = request.GET.get('student_id')
    try:
        # 중복 검사 실패
        student = Student.objects.get(student_id=student_id)
    except:
        # 중복 검사 성공
        student = None
    if student is None:
        overlap = "pass"
    else:
        overlap = "fail"
    ctx = {'overlap':overlap}

    return JsonResponse(ctx)

@login_required(login_url='/users/')
def student_list(request):
    student = Student.objects.all().order_by('-id')
    paginator = Paginator(student, 10)
    page = request.GET.get('page')
    students = paginator.get_page(page)
    ctx = {
        'students':students,
    }
    return render(request, 'students/student_list.html', ctx)

# 학생 정보 수정 페이지
@login_required(login_url='/users/')
def student_detail(request, pk):
    students = Student.objects.all()
    ctx = {
        'students':students
    }
    student = get_object_or_404(Student, pk=pk)
    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save(commit=False)
            student.student_id = request.POST.get('student_id')
            student.name = request.POST.get('name')
            student.phone_number = request.POST.get('phone_number')
            student.email = request.POST.get('email')
            student.status = request.POST.get('status')
            student.save()
            return redirect('students:student_list')
    
    else:
        form = StudentForm(instance=student)
    return render(request,'students/student_detail.html',{'form':form})

# 학생 정보 삭제 페이지
@login_required(login_url='/users/')
def student_remove(request, pk):
    students = Student.objects.all()
    ctx = {
        'students':students
    }
    student = get_object_or_404(Student, pk=pk)
    if request.method == "POST":
        student.delete()
        return redirect('students:student_list')
    
    else:
        form = StudentForm(instance=student)
    return render(request,'students/student_remove.html',{'form':form})

#학생 목록에서 조회하는 뷰
@login_required(login_url='/users/')
def list_search(request):
    search_key = request.GET.get('search_key') # 검색어 가져오기
    print(search_key)
    search_list = Student.objects.all()
    if search_key: # 만약 검색어가 존재하면
        search_list = search_list.filter(Q(name__contains=search_key)|Q(student_id__contains=search_key)|Q(phone_number__contains=search_key)|Q(email__contains=search_key)) 
    search_list = search_list.order_by('-id')
    paginator = Paginator(search_list, 10)
    page = request.GET.get('page')
    students = paginator.get_page(page)
    ctx = {
        'students': students,
    }
    return render(request, 'students/student_list_search.html', ctx)

students/templates/students/lookup_student_list.html
{% load static %}

<div id="search_student">
    <div id="search_student_list">
        <div class="container">
        <table class='table table-striped'>
            <thead>
                <tr>
                    <td><b>학번</b></td>
                    <td><b>이름</b></td>
                    <td><b>연락처</b></td>
                    <td><b>이메일</b></td>
                    <td><b>학적</b></td>
                    <td><b>수정</b></td>
                    <td><b>삭제</b></td>
                </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <td>{{student.student_id}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.phone_number}}</td>
                    <td>{{student.email}}</td>
                    <td>{{student.status}}</td>
                    <td><a href="{% url 'students:student_detail' pk=student.pk %}"><img src ="/static/edit.png"></a></td>
                    <td><a href="{% url 'students:student_remove' pk=student.pk %}"><img src ="/static/rubbish.png"></a></td>
                </tr>   
            {% endfor %} 
            </tbody>
        </table>
        </div>
    </div>
    <div class="container" id='paginator'>
        <div class="flex-item">
            {% if students.has_previous %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='{{equipments.previous_page_number}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='1' style="cursor: pointer">
            {% endif %}
        </div>
        <div class='flex-item'>
                <div style="font-size:3rem">{{students.number}}</div>
                <div style="font-size:3rem">/</div>
                <div style="font-size:3rem">{{students.paginator.num_pages}}</div>
        </div>
        <div class="flex-item">
            {% if students.has_next %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{students.next_page_number}}' style="cursor: pointer">
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{students.paginator.num_pages}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{students.paginator.num_pages}}' style="cursor: pointer"> 
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{students.paginator.num_pages}}' style="cursor: pointer">
            {% endif %}
        </div>
    </div>
</div>
<script>
    $(function(){
        $("img[name=paginator]").click(function(){
            var search_key = $('#search_key').val();
            console.log(search_key)
            event.preventDefault()
            $.ajax({
                url:'list_search/?search_key='+ search_key + '&page=' + $(this).attr('id'),
                data:{
                    'search_key':search_key,
                },
                success:function(data){
                    $('#search_student').html(data)
                }
            })
        });
    });
</script>

students/templates/students/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'students/student_register.css' %}">
{% endblock custom_css %}
    <link rel="stylesheet" href="{% static 'students/student_register.css' %}">

{%block content%}
<div class="container">
    <div class="row">
        <div class="subtitle" style="margin-top: 50px; text-align: center;">
            <h1 style='font-weight:bold; '>학생 정보 수정</h1>
        </div>
    </div>
    <div class="row">
        <div class="rentform ">
            <form id="rent_form" action="" method="post" onkeydown="return event.key != 'Enter';" enctype="multipart/form-data">
                                                        <!-- 바코드 스캔 시 자동으로 제출되는 것 방지-->
                {% csrf_token %}
                <input style='opacity:0; cursor:default;' name="beforeAmt" id="beforeAmt" value="" onkeyup="eventKeyup(this.value)"/>
                <table class="info_table">
                    <tr>
                        <td>학번 : </td>
                        <td>{{form.student_id}}</td>
                    </tr>
                    <tr>
                        <td>이름 : </td>
                        <td>{{form.name}}</td>
                    </tr>
                    <tr>
                        <td>연락처 : </td>
                        <td>{{form.phone_number}}</td>
                    </tr>
                    <tr>
                        <td>이메일 : </td>
                        <td>{{form.email}}</td>
                    </tr>
                    <tr>
                        <td>학적 상태 : </td>
                        <td>{{form.status}}</td>
                    </tr>
                </table>
                    <div class='submit_btn_div'><input type="submit" value="수정" class='submit_btn' onclick="alert('학생 정보 수정이 완료되었습니다.')"></div>
            </form>
        </div>
    </div>
</div>
{%endblock content%}

students/templates/students/student_excel_register.html
{% extends 'base.html' %}
{% load static %}

{% block custom_script %}

{% endblock custom_script %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'excel_register.css' %}">
{% endblock custom_css %}

{%block content%}
    <div class="container">
        <div class="row">
            <div class="subtitle" style="margin-top: 50px; text-align: center;">
                <h1 style='font-weight:bold; '>학생 엑셀 파일 등록</h1>
            </div>
        </div>
        <div class="row rent_row">
            <form action="" enctype="multipart/form-data"  method="post">
            {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="등록" class='submit_btn' onclick='id_overlap_check()'>
            </form>
        </div>
    </div>
{%endblock%}

students/templates/students/student_list.html
{% extends 'base.html' %}
{% load static %}

{% block custom_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javaScript">    
        $(function(){
            $("input[name=search_button]").click(function(){
                alert('입력한 정보를 조회합니다.');
                var search_key = $('#search_key').val();
                console.log(search_key)
                event.preventDefault()
                $.ajax({
                    url:'list_search/',
                    data:{
                        'search_key':search_key,
                    },
                    success:function(data){
                        $('#search_student').html(data)
                    }
                })
            });
        });
    </script>
{% endblock custom_script %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'students/student_list.css' %}">
{% endblock custom_css %}

{% block content %}
    <div class="subtitle" style="margin-top: 50px; text-align: center;">
        <h1 style='font-weight:bold; '>학생 목록</h1>
    </div>
    <div class="container search-nav">
        <form action="" method="post">
            {% csrf_token %}
            <div class="col-item input-item">
            <input type="text" class="form-control" name="search_key" placeholder="검색할 사항을 입력하세요.(학번, 이름, 연락처, 이메일)" id="search_key">
            </div>
            <div class="col-item">
                <input class="search_btn" type="submit" value="조회" name="search_button">
            </div>
        </form>
        <div id="excel-icon-wrapper">
        <a href="{% url 'students:student_excel_download' %}"><img id="excel-icon" src="{% static 'excel.png' %}" alt=""></a>
        </div>
    </div>
    <div id="search_student">
        <div id="search_student_list">
            <div class="container">
            <table class='table table-striped'>
                <thead>
                    <tr>
                        <td><b>학번</b></td>
                        <td><b>이름</b></td>
                        <td><b>연락처</b></td>
                        <td><b>이메일</b></td>
                        <td><b>학적</b></td>
                        <td><b>수정</b></td>
                        <td><b>삭제</b></td>
                    </tr>
                </thead>
                <tbody>
                {% for student in students %}
                    <tr>
                        <td>{{student.student_id}}</td>
                        <td>{{student.name}}</td>
                        <td>{{student.phone_number}}</td>
                        <td>{{student.email}}</td>
                        <td>{{student.status}}</td>
                        <td><a href="{% url 'students:student_detail' pk=student.pk %}"><img src ="/static/edit.png"></a></td>
                        <td><a href="{% url 'students:student_remove' pk=student.pk %}"><img src ="/static/rubbish.png"></a></td>
                    </tr>   
                {% endfor %} 
                </tbody>
            </table>
            </div>
        </div>
        <div class="container" id='paginator'>
            <div class='flex-item'>
                {% if students.has_previous %}
                    <img src="{% static 'prever.png' %}" onclick="location.href='?page=1'" style="cursor: pointer">
                    <img src="{% static 'prev.png' %}" onclick="location.href='?page={{students.previous_page_number}}'" style="cursor: pointer">
                {% else %}
                    <img src="{% static 'prever.png' %}" onclick="location.href='?page=1'" style="cursor: pointer">
                    <img src="{% static 'prev.png' %}" onclick="location.href='?page=1'" style="cursor: pointer">
                {% endif %}
            </div>
            <div class='flex-item'>
                    <div style="font-size:3rem">{{students.number}}</div>
                    <div style="font-size:3rem">/</div>
                    <div style="font-size:3rem">{{students.paginator.num_pages}}</div>
            </div>
            <div class='flex-item'>
                {% if students.has_next %}
                    <img src="{% static 'next.png' %}" onclick="location.href='?page={{students.next_page_number}}'" style="cursor: pointer">
                    <img src="{% static 'nexter.png' %}" onclick="location.href='?page={{students.paginator.num_pages}}'" style="cursor: pointer">
                {% else %}
                    <img src="{% static 'next.png' %}" onclick="location.href='?page={{students.paginator.num_pages}}'" style="cursor: pointer">
                    <img src="{% static 'nexter.png' %}" onclick="location.href='?page={{students.paginator.num_pages}}'" style="cursor: pointer">
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}
    

students/templates/students/student_list_search.html
{% load static %}

<div id="search_student">
    <div id="search_student_list">
        <div class="container">
        <table class='table table-striped'>
            <thead>
                <tr>
                    <td><b>학번</b></td>
                    <td><b>이름</b></td>
                    <td><b>연락처</b></td>
                    <td><b>이메일</b></td>
                    <td><b>학적</b></td>
                    <td><b>수정</b></td>
                    <td><b>삭제</b></td>
                </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <td>{{student.student_id}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.phone_number}}</td>
                    <td>{{student.email}}</td>
                    <td>{{student.status}}</td>
                    <td><a href="{% url 'students:student_detail' pk=student.pk %}"><img src ="/static/edit.png"></a></td>
                    <td><a href="{% url 'students:student_remove' pk=student.pk %}"><img src ="/static/rubbish.png"></a></td>
                </tr>   
            {% endfor %} 
            </tbody>
        </table>
        </div>
    </div>
    <div class="container" id='paginator'>
        <div class="flex-item">
            {% if students.has_previous %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='{{equipments.previous_page_number}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='1' style="cursor: pointer">
            {% endif %}
        </div>
        <div class='flex-item'>
                <div style="font-size:3rem">{{students.number}}</div>
                <div style="font-size:3rem">/</div>
                <div style="font-size:3rem">{{students.paginator.num_pages}}</div>
        </div>
        <div class="flex-item">
            {% if students.has_next %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{students.next_page_number}}' style="cursor: pointer">
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{students.paginator.num_pages}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{students.paginator.num_pages}}' style="cursor: pointer"> 
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{students.paginator.num_pages}}' style="cursor: pointer">
            {% endif %}
        </div>
    </div>
</div>
<script>
    $(function(){
        $("img[name=paginator]").click(function(){
            var search_key = $('#search_key').val();
            console.log(search_key)
            event.preventDefault()
            $.ajax({
                url:'list_search/?search_key='+ search_key + '&page=' + $(this).attr('id'),
                data:{
                    'search_key':search_key,
                },
                success:function(data){
                    $('#search_student').html(data)
                }
            })
        });
    });
</script>

students/templates/students/student_register.html
{% extends 'base.html' %}
{% load static %}

{% block custom_script %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javaScript">
        function eventKeyup(str){
            let str2 = str.slice(3, 10)
            $("#id_student_id").val(str2);    // jQuery 이용
        }
        $(function(){
            $("input[name=cur_focus]").click(function(){
                alert('학생증 QR코드를 스캔해주세요.')
                $("input[name=beforeAmt]").focus();
                $('input[id=id_student_id]').css('background-color', 'rgba(0, 100, 214, 0.25)');
            });
        });

        function id_overlap_check() {
            if ($('#id_student_id').val() == '') {
                alert('학생 번호를 입력해주세요.');
                event.preventDefault()
                return false;
            }
            else if ($('#id_name').val() == '') {
                alert('이름을 입력해주세요.');
                event.preventDefault()
                return false;
            }
            else if ($('#id_phone_number').val() == '') {
                alert('연락처를 입력해주세요.');
                event.preventDefault()
                return false;
            }
            else if ($('#id_email').val() == '') {
                alert('이메일을 입력해주세요.');
                event.preventDefault()
                return false;
            }

            id_overlap_input = document.querySelector('input[name="student_id"]');
            $.ajax({
                url: "{% url 'students:student_overlap_check' %}",
                data: {
                    'student_id': id_overlap_input.value
                },
                datatype:'json',
                success: function (data) {
                    if (data['overlap'] == 'fail') {
                        alert("이미 등록되어 있는 학생입니다.");
                        id_overlap_input.focus();
                        cancelFormSubmission();
                        return false;
                        document.querySelector('.submit_btn').setAttribute('disabled', true);
                        
                    } else {
                        alert('학생 등록이 완료되었습니다.');
                        document.querySelector('.submit_btn').removeAttribute('disabled');
                        return;
                    }
                }
            })
        }
    </script>
{% endblock custom_script %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'students/student_register.css' %}">
{% endblock custom_css %}

{%block content%}

<div class="container">
        <div class="subtitle" style="margin-top: 50px; text-align: center;">
            <h1 style='font-weight:bold; '>학생 등록</h1>
        </div>
    <div class="row">
        <div class="rentform ">
            <form id="rent_form" action="" method="post" onkeydown="return event.key != 'Enter';" enctype="multipart/form-data">
                                                        <!-- 바코드 스캔 시 자동으로 제출되는 것 방지-->
                {% csrf_token %}
                <input style='opacity:0; cursor:default;' name="beforeAmt" id="beforeAmt" value="" onkeyup="eventKeyup(this.value)"/>
                <table class="info_table">
                    <tr>
                        <td>학번 : </td>
                        <td>{{student_form.student_id}}</td>
                        <td id='scan_td'><input type='button' name='cur_focus' value='학생증 스캔' class='scan_btn'></td>
                    </tr>
                    <tr>
                        <td>이름 : </td>
                        <td>{{student_form.name}}</td>
                    </tr>
                    <tr>
                        <td>연락처 : </td>
                        <td>{{student_form.phone_number}}</td>
                    </tr>
                    <tr>
                        <td>이메일 : </td>
                        <td>{{student_form.email}}</td>
                    </tr>
                    <tr>
                        <td>학적 상태 : </td>
                        <td>{{student_form.status}}</td>
                    </tr>
                </table>
                    <div class='submit_btn_div'><input type="submit" value="등록" class='submit_btn' onclick='id_overlap_check()'></div>
            </form>
        </div>
    </div>
</div>

{%endblock%}

students/templates/students/student_remove.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'students/student_register.css' %}">
{% endblock custom_css %}
    <link rel="stylesheet" href="{% static 'students/student_register.css' %}">

{%block content%}
<div class="container">
    <div class="row">
        <div class="subtitle" style="margin-top: 50px; text-align: center;">
            <h1 style='font-weight:bold; '>학생 정보 삭제</h1>
        </div>
    </div>
    <div class="row">
        <div class="rentform ">
            <form id="rent_form" action="" method="post" onkeydown="return event.key != 'Enter';" enctype="multipart/form-data">
                                                        <!-- 바코드 스캔 시 자동으로 제출되는 것 방지-->
                {% csrf_token %}
                <input style='opacity:0; cursor:default;' name="beforeAmt" id="beforeAmt" value="" onkeyup="eventKeyup(this.value)"/>
                <table class="info_table">
                    <tr>
                        <td>학번 : </td>
                        <td>{{form.student_id}}</td>
                    </tr>
                    <tr>
                        <td>이름 : </td>
                        <td>{{form.name}}</td>
                    </tr>
                    <tr>
                        <td>연락처 : </td>
                        <td>{{form.phone_number}}</td>
                    </tr>
                    <tr>
                        <td>이메일 : </td>
                        <td>{{form.email}}</td>
                    </tr>
                    <tr>
                        <td>학적 상태 : </td>
                        <td>{{form.status}}</td>
                    </tr>
                </table>
                    <div class='submit_btn_div'><input type="submit" value="삭제" class='submit_btn' onclick="alert('학생 정보 삭제가 완료되었습니다.')"></div>
            </form>
        </div>
    </div>
</div>
{%endblock content%}