EquipManage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from managements import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managements.urls')),
    path('equipment/', include('equipments.urls')),
    path('student/', include('students.urls')),
    path('users/', include('users.urls')),
    path('graphs/', include('graphs.urls')),
    path('receivecode.html/', views.receivecode, name='receivecode'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipments/urls.py
from django.urls import path, include
from equipments import views

app_name = 'equipments'

urlpatterns = [
    path('', views.equipment_register, name="equipment_register"),
    path('list/', views.equipment_list, name='equipment_list'),
    path('list/list_search/', views.list_search, name='list_search'),
    path('list/search_rent_status/', views.search_rent_status, name='search_rent_status'),
    path('list/equip_excel_download', views.equip_excel_download, name='equip_excel_download'),
    path('equip_check/', views.equipment_overlap_check, name="equipment_overlap_check"),
    path('detail/<int:pk>/',views.equipment_detail, name='equipment_detail'),
    path('remove/<int:pk>/',views.equipment_remove, name='equipment_remove'),
    path('remove/check/', views.equip_remove_check, name='equip_remove_check'),
    path('equip_excel_register/', views.equip_excel_register, name='equip_excel_register'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns=[
    path('', views.staff_login, name="staff_login"), 
    path('users/login_check', views.login_success_check, name="login_success_check"), 
    path('logout/', views.staff_logout, name="staff_logout"), 
]

equipments/models.py
from django.db import models

class Equipment(models.Model):
    TYPE_NOTEBOOK = 'laptop'
    TYPE_TABLET = 'tablet'
    TYPE_SENSOR = 'sensor'
    EQUIP_TYPE_CHOICES = (
        (TYPE_NOTEBOOK,'노트북'),
        (TYPE_TABLET, '태블릿'),
        (TYPE_SENSOR, '센서'),
    )

    STATUS_POSSIBLE = 'possible'
    STATUS_IMPOSSIBLE = 'impossible'
    STATUS_PENDING = 'pending'
    EQUIP_STATUS_CHOICES = (
        (STATUS_POSSIBLE,'대여가능'),
        (STATUS_IMPOSSIBLE, '대여중'),
        (STATUS_PENDING, '보류'),
    )

    equip_id = models.CharField(unique=True,max_length=255)
    equip_type = models.CharField(max_length=20, choices = EQUIP_TYPE_CHOICES, null=True, blank=True)
    # rent_status = models.BooleanField(default=False) -> 반납 보류 추가
    rent_status = models.CharField(max_length=20, choices = EQUIP_STATUS_CHOICES, default=STATUS_POSSIBLE)

    def __str__(self):
        return self.equip_id

equipments/forms.py
from django import forms
from equipments.models import Equipment

class EquipForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ('equip_id', 'equip_type',)

equipments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Equipment
from managements.models import RentManage
from students.models import Student
from .forms import EquipForm
from django.contrib import messages
import json
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django import forms
from django.core.validators import FileExtensionValidator
from django.db import IntegrityError
import xlwt

@login_required(login_url='/users/')
def equipment_register(request):
    if request.method == 'POST':
        equipment_form = EquipForm(request.POST)
        if equipment_form.is_valid():
            equip_info = equipment_form.save(commit=False)
            equip_info.save()
            return redirect('equipments:equipment_list')
        else :
            return redirect('equipments:equipment_register')
    else:
        equipment_form = EquipForm()
        return render(request, 'equipments/equipment_register.html', {'equipment_form':equipment_form})

# 기자재 excel 한꺼번에 등록
class UploadFileForm(forms.Form):
    file = forms.FileField()

@login_required(login_url='/users/')
def equip_excel_register(request):
    if request.method == "POST":
        try:
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                request.FILES['file'].save_to_database(
                    name_columns_by_row=0, # 첫 번째 행 제목
                    model=Equipment,
                    mapdict=['equip_id', 'equip_type'])
                return redirect('equipments:equipment_list')
            else:
                return redirect('equipments:equip_excel_register')
        except IntegrityError:
            return redirect('equipments:equip_excel_register')
    else:
        form = UploadFileForm()
    return render(request, 'equipments/equip_excel_register.html', {'form': form})

# 기자재 리스트 엑셀 export
@login_required(login_url='/users/')
def equip_excel_download(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="equipments.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Equipments')
    row_num = 0 # sheet header
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    
    columns = ['물품번호', '물품종류', '대여상태']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    
    rows = Equipment.objects.all().values_list('equip_id', 'equip_type', 'rent_status')
    for row in rows :
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    
    wb.save(response)
    return response

# 기자재 물품 번호 중복 확인
@login_required(login_url='/users/')
def equipment_overlap_check(request):
    equip_id = request.GET.get('equip_id')
    try:
        # 중복 검사 실패
        equip = Equipment.objects.get(equip_id=equip_id)
    except:
        # 중복 검사 성공
        equip = None
    if equip is None:
        overlap = "pass"
    else:
        overlap = "fail"
    ctx = {'overlap':overlap}

    return JsonResponse(ctx)

# 기자재 리스트 페이지
@login_required(login_url='/users/')
def equipment_list(request):
    equip = Equipment.objects.all().order_by('-id')
    paginator = Paginator(equip, 10)
    page = request.GET.get('page')
    rents = RentManage.objects.all()
    equipments = paginator.get_page(page)
    ctx = {
        'equipments': equipments,
        'rents':rents,
    }
    return render(request, 'equipments/equipment_list.html', ctx)

@login_required(login_url='/users/')
def equipment_detail(request, pk):
    equipments = Equipment.objects.all()
    rents = RentManage.objects.all()
    ctx = {
        'equipments':equipments,
        'rents':rents,
    }
    equip = get_object_or_404(Equipment, pk=pk)
    if request.method == "POST":
        form = EquipForm(request.POST, instance=equip)
        if form.is_valid():
            equip = form.save(commit=False)
            equip.equip_id = request.POST.get('equip_id')
            equip.equip_type = request.POST.get('equip_type')
            equip.save()
            return redirect('equipments:equipment_list')
    
    else:
        form = EquipForm(instance=equip)
    return render(request,'equipments/equipment_detail.html',{'form':form})

# 기자개 정보 삭제 페이지
@login_required(login_url='/users/')
def equipment_remove(request, pk):
    equipments = Equipment.objects.all()
    rents = RentManage.objects.all()
    ctx = {
        'equipments':equipments,
        'rents':rents,
    }
    equip = get_object_or_404(Equipment, pk=pk)
    if request.method == "POST":
        if equip.rent_status == 'impossible' or equip.rent_status == 'pending':
            return redirect('equipments:equipment_list')
        elif equip.rent_status == 'possible':
            equip.delete()
            return redirect('equipments:equipment_list')
    
    else:
        form = EquipForm(instance=equip)
    return render(request,'equipments/equipment_remove.html',{'form':form})

@login_required(login_url='/users/')
def equip_remove_check(request):
    equip_id = request.GET.get('equip_id')
    equip = Equipment.objects.get(equip_id=equip_id)
    if equip.rent_status == 'possible':
        remove="pass"
    else:
        remove="fail"
    ctx = {'remove':remove}
    return JsonResponse(ctx)

@login_required(login_url='/users/')
def list_search(request):
    selected_equip_id = request.GET.get('search_input')
    selected_equip_type = request.GET.get('search_select')
    rents = RentManage.objects.all()

    if selected_equip_type == "":
        selected_equip_type = False
    
    if selected_equip_id and selected_equip_type:
        search_list = Equipment.objects.all().filter(equip_id__contains=selected_equip_id, equip_type__contains=selected_equip_type)

    elif selected_equip_id:
        search_list = Equipment.objects.all().filter(equip_id__contains=selected_equip_id)

    elif selected_equip_type:
        search_list = Equipment.objects.all().filter(equip_type__contains=selected_equip_type)

    else:
        search_list = Equipment.objects.all()

    search_list = search_list.order_by('-id')
    paginator = Paginator(search_list, 10)
    page = request.GET.get('page')
    equipments = paginator.get_page(page)
    
    ctx = {
        'equipments':equipments,
        'rents':rents,
    }
    return render(request, 'equipments/equip_list_search_1.html', ctx)

#기자재 리스트에서 대여 상태(rent_status) 검색하는 뷰
@login_required(login_url='/users/')
def search_rent_status(request):
    search_status = request.GET.get('search_status')
    rents = RentManage.objects.all()

    if search_status =="":
            search_status = None
    
    if search_status is not None:
            search_list = Equipment.objects.all().filter(rent_status=search_status)
    else:
            search_list = Equipment.objects.all()

    search_list = search_list.order_by('-id')
    paginator = Paginator(search_list, 10)
    page = request.GET.get('page')
    equipments = paginator.get_page(page)

    ctx = {
            "equipments":equipments,
            "rents":rents,
    }

    return render(request, 'equipments/equip_list_search_2.html', ctx)

equipments/templates/equipments/equip_list_search_1.html
{% load static %}

<div id="search_equip">
    <div id="search_equip_list">
        <div class="container">
            <table class='table table-striped'>
                <thead>
                    <tr>
                        <td><b>물품 번호</b></td>
                        <td><b>물품 종류</b></td>
                        <td><b>대여 상태</b></td>
                        <td><b>대여자 학번</b></td>
                        <td><b>대여자 이름</b></td>
                        <td><b>대여일</b></td>
                        <td><b>수정</b></td>
                        <td><b>삭제</b></td>
                    </tr>
                </thead>
                <tbody>
                
                {% for equip in equipments %}
                    <tr>
                        <td>{{equip.equip_id}}</td>
                        <td>{{equip.get_equip_type_display}}</td>
                        {% if equip.rent_status == 'possible' %}
                            <td id='rent_possible'>대여 가능</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        {% elif equip.rent_status == 'impossible' %}
                            <td id='rent_impossible'>대여중</td>
                            {%for rent in rents%}
                                {%if rent.equip.equip_id == equip.equip_id%}
                                <td>{{rent.student.student_id}}</td>
                                <td>{{rent.student.name}}</td>
                                <td>{{rent.rent_date | date:'Y-m-d'}} &nbsp; &nbsp; {{rent.rent_date | date:'h:i A'}}</td>
                                {%endif%}
                            {%endfor%}
                        {% else %}
                            <td id='rent_pending'>반납 보류</td>
                            {%for rent in rents%}
                                {%if rent.equip.equip_id == equip.equip_id%}
                                <td>{{rent.student.student_id}}</td>
                                <td>{{rent.student.name}}</td>
                                <td>{{rent.rent_date | date:'Y-m-d'}} &nbsp; &nbsp; {{rent.rent_date | date:'h:i A'}}</td>
                                {%endif%}
                            {%endfor%}
                        {% endif %}
                        <td><a href="{% url 'equipments:equipment_detail' pk=equip.pk %}"><img src ="/static/edit.png"></a></td>
                        <td><a href="{% url 'equipments:equipment_remove' pk=equip.pk %}"><img src ="/static/rubbish.png"></a></td>
                    </tr>   
                {% endfor %} 
                </tbody>
            </table>
        </div>
    </div>
    <div class="container" id='paginator'>
        <div class="flex-item">
            {% if equipments.has_previous %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='{{equipments.previous_page_number}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='1' style="cursor: pointer">
            {% endif %}
        </div>
        <div class="flex-item">
                <div style="font-size:3rem">{{equipments.number}}</div>
                <div style="font-size:3rem">/</div>
                <div style="font-size:3rem">{{equipments.paginator.num_pages}}</div>
        </div>
        <div class="flex-item">
            {% if equipments.has_next %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{equipments.next_page_number}}' style="cursor: pointer">
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{equipments.paginator.num_pages}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{equipments.paginator.num_pages}}' style="cursor: pointer"> 
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{equipments.paginator.num_pages}}' style="cursor: pointer">
            {% endif %}
        </div>
    </div>
</div>
<script>
    $(function(){
        $("img[name=paginator]").click(function(){
            var search_input = $('#search_input').val();
            var search_select = $('#search_select').val();
            event.preventDefault()
            $.ajax({
                url:'list_search/?search_input='+ search_input + '?search_select=' + search_select + '&page=' + $(this).attr('id'),
                data:{
                    'search_input':search_input, 
                    'search_select':search_select,
                },
                success:function(data){
                    $('#search_equip').html(data)
                }
            })
        });
    });
</script>

equipments/templates/equipments/equip_list_search_2.html
{% load static %}

<div id="search_equip">
    <div id="search_equip_list">
        <div class="container">
            <table class='table table-striped'>
                <thead>
                    <tr>
                        <td><b>물품 번호</b></td>
                        <td><b>물품 종류</b></td>
                        <td><b>대여 상태</b></td>
                        <td><b>대여자 학번</b></td>
                        <td><b>대여자 이름</b></td>
                        <td><b>대여일</b></td>
                        <td><b>수정</b></td>
                        <td><b>삭제</b></td>
                    </tr>
                </thead>
                <tbody>
                
                {% for equip in equipments %}
                    <tr>
                        <td>{{equip.equip_id}}</td>
                        <td>{{equip.get_equip_type_display}}</td>
                        {% if equip.rent_status == 'possible' %}
                            <td id='rent_possible'>대여 가능</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        {% elif equip.rent_status == 'impossible' %}
                            <td id='rent_impossible'>대여중</td>
                            {%for rent in rents%}
                                {%if rent.equip.equip_id == equip.equip_id%}
                                <td>{{rent.student.student_id}}</td>
                                <td>{{rent.student.name}}</td>
                                <td>{{rent.rent_date | date:'Y-m-d'}} &nbsp; &nbsp; {{rent.rent_date | date:'h:i A'}}</td>
                                {%endif%}
                            {%endfor%}
                        {% else %}
                            <td id='rent_pending'>반납 보류</td>
                            {%for rent in rents%}
                                {%if rent.equip.equip_id == equip.equip_id%}
                                <td>{{rent.student.student_id}}</td>
                                <td>{{rent.student.name}}</td>
                                <td>{{rent.rent_date | date:'Y-m-d'}} &nbsp; &nbsp; {{rent.rent_date | date:'h:i A'}}</td>
                                {%endif%}
                            {%endfor%}
                        {% endif %}
                        <td><a href="{% url 'equipments:equipment_detail' pk=equip.pk %}"><img src ="/static/edit.png"></a></td>
                        <td><a href="{% url 'equipments:equipment_remove' pk=equip.pk %}"><img src ="/static/rubbish.png"></a></td>
                    </tr>   
                {% endfor %} 
                </tbody>
            </table>
        </div>
    </div>
    <div class="container" id='paginator'>
        <div class="flex-item">
            {% if equipments.has_previous %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='{{equipments.previous_page_number}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'prever.png' %}" name='paginator' id='1' style="cursor: pointer">
                <img src="{% static 'prev.png' %}" name='paginator' id='1' style="cursor: pointer">
            {% endif %}
        </div>
        <div class="flex-item">
                <div style="font-size:3rem">{{equipments.number}}</div>
                <div style="font-size:3rem">/</div>
                <div style="font-size:3rem">{{equipments.paginator.num_pages}}</div>
        </div>
        <div class="flex-item">
            {% if equipments.has_next %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{equipments.next_page_number}}' style="cursor: pointer">
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{equipments.paginator.num_pages}}' style="cursor: pointer">
            {% else %}
                <img src="{% static 'next.png' %}" name='paginator' id='{{equipments.paginator.num_pages}}' style="cursor: pointer"> 
                <img src="{% static 'nexter.png' %}" name='paginator' id='{{equipments.paginator.num_pages}}' style="cursor: pointer">
            {% endif %}
        </div>
    </div>
</div>
<script>
    $(function(){
        $("img[name=paginator]").click(function(){
            var search_status = $('#search_status').val();
            event.preventDefault()
            $.ajax({
                url:'search_rent_status/?search_status='+ search_status + '&page=' + $(this).attr('id'),
                data:{
                    'search_status':search_status,
                },
                success:function(data){
                    $('#search_equip').html(data)
                }
            })
        });
    });
</script>

equipments/templates/equipments/equipment_list.html
{% extends 'base.html' %}
{% load static %}

{% block custom_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javaScript">    
        $(function(){
            $("input[name=search_button]").click(function(){
                alert('입력한 정보를 조회합니다.');
                var search_input = $('#search_input').val();
                var search_select = $('#search_select').val();
                $('#search_status option:eq(0)').prop("selected", true);
                event.preventDefault()
                $.ajax({
                    url:'list_search/',
                    data:{
                        'search_input':search_input, 
                        'search_select':search_select,
                    },
                    success:function(data){
                        $('#search_equip').html(data)
                    }
                })
            });
            $("input[name=search_button2]").click(function(){
                alert('기자재 상태 정보를 조회합니다.');
                var search_status = $('#search_status').val();
                $('#search_input').val('');
                $('#search_select option:eq(0)').prop("selected", true);
                event.preventDefault()
                $.ajax({
                    url:'search_rent_status/',
                    data:{
                        'search_status':search_status, 
                    },
                    success:function(data){
                        $('#search_equip').html(data)
                    }
                })
            });
        });
    </script>
{% endblock custom_script %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'equipments/equip_list.css' %}">
{% endblock custom_css %}

{% block content %}
    <div class="subtitle" style="margin-top: 50px; text-align: center;">
        <h1 style='font-weight:bold; '>기자재 목록</h1>
    </div>
    <div class="container search-nav">
        <form action="" method="post">
        {% csrf_token %}
        <div class="col-item input-item">
            <input type="text" class="form-control" name='search_input' id='search_input' placeholder="검색할 사항을 입력하세요.(물품 번호)"/>
        </div>
        <div class="col-item">    
            <select class='form-select' name="search_select" id="search_select">
                <option id="default" selected value="">기자재 종류</option>
                <option value="laptop">노트북</option>
                <option value="tablet">태블릿</option>
                <option value="sensor">센서</option>
            </select>
        </div>
        <div class="col-item">
            <input class="search_btn" type="submit" value="조회" name="search_button">
        </div>
        <div class="col-item"> 
            <select class='form-select' name="search_status" id="search_status">
                <option value="">기자재 상태</option>
                <option value="possible">대여 가능</option>
                <option value="impossible">대여 중</option>
                <option value="pending">반납 보류</option>
            </select>
        </div>
        <div class="col-item">
            <input class="search_btn" type="submit" value="조회" name="search_button2">
        </div>
        </form>
        <div id="excel-icon-wrapper">
        <a href="{% url 'equipments:equip_excel_download' %}"><img id="excel-icon" src="{% static 'excel.png' %}" alt=""></a>
        </div>
    </div>
    <div id="search_equip">
        <div id="search_equip_list">
            <div class="container">
                <table class='table table-striped'>
                    <thead>
                        <tr>
                            <td><b>물품 번호</b></td>
                            <td><b>물품 종류</b></td>
                            <td><b>대여 상태</b></td>
                            <td><b>대여자 학번</b></td>
                            <td><b>대여자 이름</b></td>
                            <td><b>대여일</b></td>
                            <td><b>수정</b></td>
                            <td><b>삭제</b></td>
                        </tr>
                    </thead>
                    <tbody>
                    
                    {% for equip in equipments %}
                        <tr>
                            <td>{{equip.equip_id}}</td>
                            <td>{{equip.get_equip_type_display}}</td>
                            {% if equip.rent_status == 'possible' %}
                                <td id='rent_possible'>대여 가능</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            {% elif equip.rent_status == 'impossible' %}
                                <td id='rent_impossible'>대여중</td>
                                {%for rent in rents%}
                                    {%if rent.equip.equip_id == equip.equip_id%}
                                    <td>{{rent.student.student_id}}</td>
                                    <td>{{rent.student.name}}</td>
                                    <td>{{rent.rent_date | date:'Y-m-d'}} &nbsp; &nbsp; {{rent.rent_date | date:'h:i A'}}</td>
                                    {%endif%}
                                {%endfor%}
                            {% else %}
                                <td id='rent_pending'>반납 보류</td>
                                {%for rent in rents%}
                                    {%if rent.equip.equip_id == equip.equip_id%}
                                    <td>{{rent.student.student_id}}</td>
                                    <td>{{rent.student.name}}</td>
                                    <td>{{rent.rent_date | date:'Y-m-d'}} &nbsp; &nbsp; {{rent.rent_date | date:'h:i A'}}</td>
                                    {%endif%}
                                {%endfor%}
                            {% endif %}
                            <td><a href="{% url 'equipments:equipment_detail' pk=equip.pk %}"><img src ="/static/edit.png"></a></td>
                            <td><a href="{% url 'equipments:equipment_remove' pk=equip.pk %}"><img src ="/static/rubbish.png"></a></td>
                        </tr>   
                    {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container" id='paginator'>
            <div class='flex-item'>
                {% if equipments.has_previous %}
                    <img src="{% static 'prever.png' %}" onclick="location.href='?page=1'" style="cursor: pointer">
                    <img src="{% static 'prev.png' %}" onclick="location.href='?page={{equipments.previous_page_number}}'" style="cursor: pointer">
                {% else %}
                    <img src="{% static 'prever.png' %}" onclick="location.href='?page=1'" style="cursor: pointer">
                    <img src="{% static 'prev.png' %}" onclick="location.href='?page=1'" style="cursor: pointer">
                {% endif %}
            </div>
            <div class='flex-item'>
                    <div style="font-size:3rem">{{equipments.number}}</div>
                    <div style="font-size:3rem">/</div>
                    <div style="font-size:3rem">{{equipments.paginator.num_pages}}</div>
            </div>
            <div class='flex-item'>
                {% if equipments.has_next %}
                    <img src="{% static 'next.png' %}" onclick="location.href='?page={{equipments.next_page_number}}'" style="cursor: pointer">
                    <img src="{% static 'nexter.png' %}" onclick="location.href='?page={{equipments.paginator.num_pages}}'" style="cursor: pointer">
                {% else %}
                    <img src="{% static 'next.png' %}" onclick="location.href='?page={{equipments.paginator.num_pages}}'" style="cursor: pointer">
                    <img src="{% static 'nexter.png' %}" onclick="location.href='?page={{equipments.paginator.num_pages}}'" style="cursor: pointer">
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}
    

equipments/templates/equipments/equipment_register.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'equipments/equip_register.css' %}">
{% endblock custom_css %}

{% block custom_script %}
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'equipments/equip_register.js' %}"></script>
    <script type="text/javaScript">

        function id_overlap_check() {
            if ($('#id_equip_id').val() == '') {
                alert('기자재 번호를 입력해주세요.');
                event.preventDefault();
                return false;
            }
            else if ($('#id_equip_type').val() == '') {
                alert('물품 종류를 선택해주세요.');
                event.preventDefault();
                return false;
            }

            id_overlap_input = document.querySelector('input[name="equip_id"]');
            $.ajax({
                url: "{% url 'equipments:equipment_overlap_check' %}",
                data: {
                    'equip_id': id_overlap_input.value
                },
                datatype:'json',
                success: function (data) {
                    if (data['overlap'] == 'fail') {
                        alert("이미 등록되어 있는 기자재입니다.");
                        id_overlap_input.focus();
                        cancelFormSubmission();
                        return false;
                        document.querySelector('.submit_btn').setAttribute('disabled', true);
                        
                    } else {
                        alert('기자재 등록이 완료되었습니다.');
                        document.querySelector('.submit_btn').removeAttribute('disabled');
                        return;
                    }
                }
            })
        }
        $(function(){
            $("input[name=cur_focus2]").click(function(){
                alert('기자재 바코드를 스캔해주세요.')
                $("input[name=equip_id]").focus();
                $('input[id=id_equip_id]').css('background-color', 'rgba(0, 100, 214, 0.25)');
            });
        }); 
    </script>
{% endblock custom_script %}

{%block content%}
    <div class="container">
        <div class="row">
            <div class="subtitle" style="margin-top: 50px; text-align: center;">
                <h1 style='font-weight:bold; '>기자재 등록</h1>
            </div>
        </div>
        <div class="row rent_row">
            <div class="rentform">
                <form id="rent_form" action="" method="post" onkeydown="return event.key != 'Enter';" enctype="multipart/form-data">
                                                            <!-- 바코드 스캔 시 자동으로 제출되는 것 방지-->
                    {% csrf_token %}
                    <table class="info_table">
                    <tr>
                        <td>물품 번호 : </td>
                        <td>{{equipment_form.equip_id}}</td>
                        <td id='scan_td'><input type="button" name='cur_focus2' value='기자재 스캔' class='scan_btn'></td>
                    </tr>
                    <tr>
                        <td>물품 종류 : </td>
                        <td>{{equipment_form.equip_type}}</td>
                    </tr>
                    </table>
                    <div class='submit_btn_div'><input type="submit" value="등록" class='submit_btn' onclick='id_overlap_check()'></div>
                </form>
            </div>
        </div>
    </div>
{%endblock%}