EquipManage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from managements import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managements.urls')),
    path('equipment/', include('equipments.urls')),
    path('student/', include('students.urls')),
    path('users/', include('users.urls')),
    path('graphs/', include('graphs.urls')),
    path('receivecode.html/', views.receivecode, name='receivecode'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipments/urls.py
from django.urls import path, include
from equipments import views

app_name = 'equipments'

urlpatterns = [
    path('', views.equipment_register, name="equipment_register"),
    path('list/', views.equipment_list, name='equipment_list'),
    path('list/list_search/', views.list_search, name='list_search'),
    path('list/search_rent_status/', views.search_rent_status, name='search_rent_status'),
    path('list/equip_excel_download', views.equip_excel_download, name='equip_excel_download'),
    path('equip_check/', views.equipment_overlap_check, name="equipment_overlap_check"),
    path('detail/<int:pk>/',views.equipment_detail, name='equipment_detail'),
    path('remove/<int:pk>/',views.equipment_remove, name='equipment_remove'),
    path('remove/check/', views.equip_remove_check, name='equip_remove_check'),
    path('equip_excel_register/', views.equip_excel_register, name='equip_excel_register'),
]

graphs/urls.py
from django.urls import path
from . import views

app_name = 'graphs'

urlpatterns = [
    path('', views.graph_main, name='graph_main'),
    path('laptop/', views.graph_laptop, name='graph_laptop'),
    path('tablet/', views.graph_tablet, name='graph_tablet'),
    path('sensor/', views.graph_sensor, name='graph_sensor'),
]

managements/urls.py
from django.urls import path, include
from managements import views

app_name = 'managements'

urlpatterns = [
    path('',views.main_page, name="main_page"),

    # 대여 관련
    path('rent/', views.rent, name="rent"),
    path('rent/search/', views.lookup_student, name="lookup_student"),
    path('rent/rent_overlap_check/', views.rent_overlap_check, name='rent_overlap_check'),# 대여중인 기자재 중복 검사
    path('rent/rent_list/', views.rent_list, name="rent_list"),
    path('rent/rent_detail_page/<int:pk>/', views.rent_detail_page, name="rent_detail_page"),
    path('rent/resend_pledge/<int:pk>/', views.resend_pledge, name="resend_pledge"),
    path('rent/rent_list/search_rent_list/', views.search_rent_list, name="search_rent_list"),
    path('rent/rent_list/search_rent_pledge/', views.search_rent_pledge, name="search_rent_pledge"),
    path('rent/rent_list/rent_excel_download', views.rent_excel_download, name='rent_excel_download'),
    path('rent/activate/<int:pk>/', views.activate, name="activate"),
    path('rent/email_success/', views.email_success, name="email_success"),

    # 반납 관련
    path('return/', views.return_, name="return_"),
    path('return/return_exist_check/', views.return_exist_check, name='return_exist_check'),# 반납 시 대여 리스트에 있는지 검사
    path('return/return_result/<int:pk>/<str:manager>/', views.return_result, name='return_result'),
    path('return/return_list/', views.return_list, name="return_list"),
    path('return/return_list/search_return_list/', views.search_return_list, name="search_return_list"),
    path('return/reurn_list/return_excel_download/', views.return_excel_download, name="return_excel_download"),
    path('return/return_info/', views.return_, name="return_info"),

    # 보류 관련
    path('return/pending/<int:pk>/<str:manager>/', views.pending, name="pending"),
    path('return/pending/pending_result/<int:pk>/<str:manager>/', views.pending_result, name="pending_result"),
    path('return/pending_list/', views.pending_list, name="pending_list"),
    path('return/pending_list/search_pending_list/', views.search_pending_list, name="search_pending_list"),
    path('return/pending_list/pending_excel_download/', views.pending_excel_download, name='pending_excel_download'),
    path('return/pending_detail_page/<int:pk>/', views.pending_detail, name="pending_detail_page"),
    path('return/pending_detail_page/return/<int:pk>/', views.pending_to_return, name="pending_to_return"), # 보류=>반납
    path('return/pending_overlap_check/', views.pending_overlap_check, name="pending_overlap_check"),
]

students/urls.py
from django.urls import path, include
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.student_register, name='student_register'),
    path('list/', views.student_list, name='student_list'),
    path('list/list_search/', views.list_search, name='list_search'),
    path('list/student_excel_download/', views.student_excel_download, name='student_excel_download'),
    path('student_check/', views.student_overlap_check, name='student_overlap_check'),
    path('detail/<int:pk>/',views.student_detail, name='student_detail'),
    path('remove/<int:pk>/',views.student_remove, name='student_remove'),
    path('student_excel_register/', views.student_excel_register, name='student_excel_register'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns=[
    path('', views.staff_login, name="staff_login"), 
    path('users/login_check', views.login_success_check, name="login_success_check"), 
    path('logout/', views.staff_logout, name="staff_logout"), 
]

templates/base.html
{% load static %}
<html>
    <head>
        <title>IT공학과 기자재 관리</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
	    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        {% block custom_script %}
        {% endblock %}
        {% block custom_css %}
        {% endblock %}
    </head>
    <body>
        <div class="main">
            <div id="navbar">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="{% url 'managements:main_page' %}">숙명여대 IT공학과 기자재 관리 페이지</a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                {% if user.is_authenticated %}
                                <a href="{% url 'users:staff_logout' %}" class="dropdown-toggle" aria-expanded="false">로그아웃</span></a>
                                {%else%}
                                <a href="{% url 'users:staff_login' %}" class="dropdown-toggle" aria-expanded="false">관리자 로그인</a>
                                {%endif%}
                                </li>
                            </ul>
                            {% if user.is_authenticated %}
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                <a href="{% url 'graphs:graph_main' %}" class="dropdown-toggle" aria-expanded="false">통계</span></a>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="nav-item dropdown">
                                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  학생  </a>
                                    <ul class="dropdown-menu fade-up">
                                    <li><a class="dropdown-item" href="{% url 'students:student_register' %}"> 학생 등록</a></li>
                                    <li><a class="dropdown-item" href="{% url 'students:student_list' %}"> 학생 목록 </a></li>
                                    <li><a class="dropdown-item" href="{% url 'students:student_excel_register' %}">파일 업로드</a></li>
                                    </ul>
                                </li>
                            </ul>     
                            <ul class="nav navbar-nav navbar-right">
                                <li class="nav-item dropdown">
                                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  기자재  </a>
                                    <ul class="dropdown-menu fade-up">
                                    <li><a class="dropdown-item" href="{% url 'equipments:equipment_register' %}"> 기자재 등록</a></li>
                                    <li><a class="dropdown-item" href="{% url 'equipments:equipment_list' %}"> 기자재 목록 </a></li>
                                    <li><a class="dropdown-item" href="{% url 'equipments:equip_excel_register' %}">파일 업로드</a></li>
                                    </ul>
                                </li>
                            </ul>      
                            <ul class="nav navbar-nav navbar-right">
                                <li class="nav-item dropdown">
                                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  반납  </a>
                                    <ul class="dropdown-menu fade-up">
                                    <li><a class="dropdown-item" href="{% url 'managements:return_' %}"> 반납 </a></li>
                                    <li><a class="dropdown-item" href="{% url 'managements:return_list' %}"> 반납 목록</a></li>
                                    <li><a class="dropdown-item" href="{% url 'managements:pending_list' %}"> 보류 목록 </a></li>
                                    </ul>
                                </li>
                            </ul>         
                            <ul class="nav navbar-nav navbar-right">
                                <li class="nav-item dropdown">
                                    <a style="margin-right:15px;"class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  대여  </a>
                                    <ul class="dropdown-menu fade-up">
                                    <li><a class="dropdown-item" href="{% url 'managements:rent' %}"> 대여 </a></li>
                                    <li><a class="dropdown-item" href="{% url 'managements:rent_list' %}"> 대여 목록</a></li>
                                    </ul>
                                </li>
                            </ul>                                               
                            {%endif%}
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
            </div>
            <div id="main_content"> 
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div class="footer_wrap">
            <div class="footer">
                <p>&copy; 2021 졸업 프로젝트 - 포어스(For Us)</p>
            </div>
        </div>
    </body>
</html>