EquipManage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from managements import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managements.urls')),
    path('equipment/', include('equipments.urls')),
    path('student/', include('students.urls')),
    path('users/', include('users.urls')),
    path('graphs/', include('graphs.urls')),
    path('receivecode.html/', views.receivecode, name='receivecode'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managements/urls.py
from django.urls import path, include
from managements import views

app_name = 'managements'

urlpatterns = [
    path('',views.main_page, name="main_page"),

    # 대여 관련
    path('rent/', views.rent, name="rent"),
    path('rent/search/', views.lookup_student, name="lookup_student"),
    path('rent/rent_overlap_check/', views.rent_overlap_check, name='rent_overlap_check'),# 대여중인 기자재 중복 검사
    path('rent/rent_list/', views.rent_list, name="rent_list"),
    path('rent/rent_detail_page/<int:pk>/', views.rent_detail_page, name="rent_detail_page"),
    path('rent/resend_pledge/<int:pk>/', views.resend_pledge, name="resend_pledge"),
    path('rent/rent_list/search_rent_list/', views.search_rent_list, name="search_rent_list"),
    path('rent/rent_list/search_rent_pledge/', views.search_rent_pledge, name="search_rent_pledge"),
    path('rent/rent_list/rent_excel_download', views.rent_excel_download, name='rent_excel_download'),
    path('rent/activate/<int:pk>/', views.activate, name="activate"),
    path('rent/email_success/', views.email_success, name="email_success"),

    # 반납 관련
    path('return/', views.return_, name="return_"),
    path('return/return_exist_check/', views.return_exist_check, name='return_exist_check'),# 반납 시 대여 리스트에 있는지 검사
    path('return/return_result/<int:pk>/<str:manager>/', views.return_result, name='return_result'),
    path('return/return_list/', views.return_list, name="return_list"),
    path('return/return_list/search_return_list/', views.search_return_list, name="search_return_list"),
    path('return/reurn_list/return_excel_download/', views.return_excel_download, name="return_excel_download"),
    path('return/return_info/', views.return_, name="return_info"),

    # 보류 관련
    path('return/pending/<int:pk>/<str:manager>/', views.pending, name="pending"),
    path('return/pending/pending_result/<int:pk>/<str:manager>/', views.pending_result, name="pending_result"),
    path('return/pending_list/', views.pending_list, name="pending_list"),
    path('return/pending_list/search_pending_list/', views.search_pending_list, name="search_pending_list"),
    path('return/pending_list/pending_excel_download/', views.pending_excel_download, name='pending_excel_download'),
    path('return/pending_detail_page/<int:pk>/', views.pending_detail, name="pending_detail_page"),
    path('return/pending_detail_page/return/<int:pk>/', views.pending_to_return, name="pending_to_return"), # 보류=>반납
    path('return/pending_overlap_check/', views.pending_overlap_check, name="pending_overlap_check"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns=[
    path('', views.staff_login, name="staff_login"), 
    path('users/login_check', views.login_success_check, name="login_success_check"), 
    path('logout/', views.staff_logout, name="staff_logout"), 
]

equipments/models.py
from django.db import models

class Equipment(models.Model):
    TYPE_NOTEBOOK = 'laptop'
    TYPE_TABLET = 'tablet'
    TYPE_SENSOR = 'sensor'
    EQUIP_TYPE_CHOICES = (
        (TYPE_NOTEBOOK,'노트북'),
        (TYPE_TABLET, '태블릿'),
        (TYPE_SENSOR, '센서'),
    )

    STATUS_POSSIBLE = 'possible'
    STATUS_IMPOSSIBLE = 'impossible'
    STATUS_PENDING = 'pending'
    EQUIP_STATUS_CHOICES = (
        (STATUS_POSSIBLE,'대여가능'),
        (STATUS_IMPOSSIBLE, '대여중'),
        (STATUS_PENDING, '보류'),
    )

    equip_id = models.CharField(unique=True,max_length=255)
    equip_type = models.CharField(max_length=20, choices = EQUIP_TYPE_CHOICES, null=True, blank=True)
    # rent_status = models.BooleanField(default=False) -> 반납 보류 추가
    rent_status = models.CharField(max_length=20, choices = EQUIP_STATUS_CHOICES, default=STATUS_POSSIBLE)

    def __str__(self):
        return self.equip_id

managements/models.py
from django.db import models
from students.models import Student
from equipments.models import Equipment


class RentManage(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='rent_students',null=True)
    equip = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='rent_equip',null=True)
    rent_date = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=False)
    
    tag_attach = models.BooleanField(default=True)
    equip_work = models.BooleanField(default=True)
    accessories = models.BooleanField(null=True, blank=True)
    manager = models.CharField(max_length=20)


    def publish(self):
        self.rent_date = timezone.now()
        self.save()

class Equip_Picture(models.Model):
    equip_pic = models.ImageField(upload_to="equip_pic/%Y/%m/%d/", default=None)
    rent = models.ForeignKey(RentManage, on_delete=models.CASCADE)


class ReturnHistory(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    equip= models.ForeignKey(Equipment, on_delete=models.CASCADE, null=True)
    return_date = models.DateTimeField(blank=True, null=True)
    manager = models.CharField(max_length=20)


# 반납 보류 모델 추가
class PendingHistory(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    equip= models.ForeignKey(Equipment, on_delete=models.CASCADE, null=True)
    reason = models.TextField()
    pending_date = models.DateTimeField(auto_now_add=True)
    manager = models.CharField(max_length=20)

class PendingEquipPicture(models.Model):
    pending_equip_pic = models.ImageField(upload_to="pending_equip_pic/%Y/%m/%d/", default=None)
    pending = models.ForeignKey(PendingHistory, on_delete=models.CASCADE)

students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):

    STATUS_CHOICES = (
        ('재학', '재학'),
        ('휴학', '휴학'),
        ('졸업', '졸업'),
        ('자퇴', '자퇴'),
    )

    student_id = models.CharField(max_length=7, unique=True)
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    status = models.CharField(max_length=5, choices=STATUS_CHOICES, default='재학')

    def __str__(self):
        return self.student_id

managements/forms.py
from django import forms
from managements.models import RentManage, ReturnHistory


# 대여 폼
class RentForm(forms.ModelForm):
        class Meta:
                model = RentManage
                exclude = ['student', 'equip', 'rent_date','tag_attach','equip_work','accessories','manager',]

# 반납 폼
class ReturnForm(forms.Form):
        return_student = forms.CharField(max_length=100)
        return_equipment = forms.CharField(max_length=100)
        return_date = forms.DateTimeField()

managements/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import RentManage, ReturnHistory, Equip_Picture, PendingHistory, PendingEquipPicture
from students.models import Student
from equipments.models import Equipment
from managements.forms import RentForm, ReturnForm
from students.models import Student
from django.utils import timezone
from django.db import IntegrityError
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth.decorators import login_required
import xlwt
from datetime import datetime

import base64
import smtplib
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import mimetypes
import os
import requests
import json
import sys

@login_required(login_url='/users/')
def main_page(request):
    return render(request, 'managements/main.html',{})


# 대여 페이지
@login_required(login_url='/users/')
def rent(request):
        if request.method == 'POST':
                rent_student_id = request.POST.get('student_id')
                rent_equipment_id = request.POST.get('equip_id')
                tag_attach = request.POST.get('tag_attach')
                equip_work = request.POST.get('equip_work')
                manager = request.POST.get('manager')
                accessories = request.POST.get('accessories')
                
                if (accessories == "None"):
                        accessories = None
                
                rent_pics = request.FILES.getlist('file')

                rent_student = get_object_or_404(Student, student_id=rent_student_id)
                rent_equip = get_object_or_404(Equipment, equip_id=rent_equipment_id)

                rent_form = RentForm(request.POST, request.FILES)

                if rent_form.is_valid()  :
                        rent_info = rent_form.save(commit=False)
                        rent_info.student = rent_student
                        rent_info.equip = rent_equip
                        rent_info.tag_attach = tag_attach
                        rent_info.equip_work = equip_work
                        if accessories is not None:
                                rent_info.accessories = accessories
                        rent_info.manager = manager
                        rent_info.rent_date = timezone.now()
                        rent_equip.rent_status = 'impossible'
                        rent_equip.save()
                        rent_info.save()

                        for item in rent_pics:
                                images = Equip_Picture.objects.create(rent=rent_info, equip_pic=item)
                                images.save()
                       
                        current_site = get_current_site(request) 
                        html_message = render_to_string('managements/user_activate_email.html', {
                                'rent_info': rent_info,
                                'domain': current_site.domain,
                        })
                        mail_title = "숙명여자대학교 IT공학과 기자재 대여 서약서"
                        # email = EmailMultiAlternatives(subject = mail_title, body=html_message, to=[rent_student.email])
                        # email.content_subtype = 'html'
                        # email.send()
                        sendmail(rent_student.email, mail_title, html_message)
                return redirect('managements:rent_list')
        else:
                rent_form = RentForm()
                ctx = {
                        'rent_form':rent_form,
                }
                return render(request, 'managements/rent.html', ctx)

def activate(request, pk):
        rentmanage = RentManage.objects.get(pk=pk)
        rentmanage.active = True
        rentmanage.save()
        return redirect("managements:email_success")

def email_success(request):
        return render(request, 'managements/email_success.html')

# 대여 중복 검사
@login_required(login_url='/users/')
def rent_overlap_check(request):
        equip_id = request.GET.get('equip_id')
        student_id = request.GET.get('student_id')
        overlap = "init"
        try: # 기자재 존재 여부 확인
                equipment = Equipment.objects.get(equip_id=equip_id)
        except:
                equipment = None

        try: # 학생 존재 여부 확인
                student = Student.objects.get(student_id=student_id)
        except:
                student = None    

        try: # 대여 리스트 중복 여부 확인
                rent_equip = Equipment.objects.get(equip_id=equip_id)
                r_equip = RentManage.objects.get(equip=rent_equip)
        except:
                r_equip = None

        if equipment is None: # 기자재 존재하지 않을 시
                e_exist = "fail"
                overlap = 'none'
        elif equipment is not None: # 기자재 존재 시
                e_exist = "pass"
                if r_equip is None and student is not None: # 대여 가능한 기자재
                        overlap = "pass"
                elif r_equip is not None: # 이미 대여중인 기자재
                        overlap = "e_fail"
                elif r_equip is None and student is None:
                        overlap = "s_fail"

        if student is None: # 학생 존재하지 않을 시
                s_exist = "fail"
        elif student is not None: # 학생 존재 시
                s_exist = "pass"
        
        ctx = {
                'overlap': overlap, 
                'e_exist': e_exist,
                's_exist':s_exist,
        }

        return JsonResponse(ctx)

# 반납 존재 여부 검사
@login_required(login_url='/users/')
def return_exist_check(request):
        equip_id = request.GET.get('equip_id')
        student_id = request.GET.get('student_id')

        try: # 기자재 존재 여부 확인
                equipment = Equipment.objects.get(equip_id=equip_id)
        except:
                equipment = None

        try: # 학생 존재 여부 확인
                student = Student.objects.get(student_id=student_id)
        except:
                student = None    

        try: # 대여 리스트 중복 여부 확인
                rent_equip = Equipment.objects.get(equip_id=equip_id)
                rent_student = Student.objects.get(student_id=student_id)
                rent = RentManage.objects.get(equip=rent_equip, student=rent_student)
        except:
                rent = None

        if equipment is None: # 기자재 존재하지 않을 시
                e_exist = "fail"
        elif equipment is not None:
                e_exist = "pass"

        if student is None: # 학생 존재하지 않을 시
                s_exist = "fail"
        elif student is not None: # 학생 존재 시
                s_exist = "pass"

        if student is not None and equipment is not None:
                if rent is None:
                        r_exist = "fail"
                elif rent is not None:
                        r_exist = "pass" 
        else :
                r_exist = "none"

        ctx = {
                'r_exist': r_exist, 
                'e_exist': e_exist,
                's_exist':s_exist,
        }

        return JsonResponse(ctx)

#대여 현황 
@login_required(login_url='/users/')
def rent_list(request):
        rent = RentManage.objects.all().order_by('-id')
        paginator = Paginator(rent,10)
        page = request.GET.get('page')
        rents = paginator.get_page(page)
        ctx = {
                'rents':rents,
        }
        return render(request, 'managements/rent_list.html', ctx)


# 대여 리스트 엑셀 export
@login_required(login_url='/users/')
def rent_excel_download(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="rent_list.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('RentManage_rent')
    row_num = 0 # sheet header
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['학번', '이름', '학적상태', '물품번호', '물품종류', '물품태그', '기기작동', '악세서리', '대여일', '검사자', '서약서']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
        
    font_style = xlwt.XFStyle()
    rows = RentManage.objects.all().values_list('student__student_id', 'student__name', 'student__status', 'equip__equip_id', 'equip__equip_type', 'tag_attach', 'equip_work', 'accessories', 'rent_date', 'manager', 'active')
    
    rows = [[rent_date.strftime("%Y-%m-%d") if isinstance(rent_date, datetime) else rent_date for rent_date in row] for row in rows ]
    for row in rows :
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    
    wb.save(response)
    return response        

# ----------------------------------------------------------------------- #

# 반납 폼 페이지
@login_required(login_url='/users/')
def return_(request):
        if request.method =='POST':
                equip_id = request.POST.get('equip_id')
                student_id = request.POST.get('student_id')
                manager = request.POST.get('manager')

                try :   
                        student = get_object_or_404(Student, student_id=student_id)
                        equip = get_object_or_404(Equipment,equip_id=equip_id)
                        rent = get_object_or_404(RentManage, equip=equip.pk)
                        rent_images = Equip_Picture.objects.all().filter(rent=rent.pk)

managements/templates/managements/lookup_fail.html
<div id="lookup">
    등록되지 않은 학생입니다.
</div>

managements/templates/managements/pending.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'managements/rent_page.css' %}">
{% endblock custom_css %}

{%block content%}
<div class="container">
    <div class="row">
        <div class="subtitle" style="margin-top: 50px; text-align: center;">
            <h1 style='font-weight:bold; '>보류 사유 입력</h1>
        </div>
    </div>
    <div class="row">
        <div class="pendingform ">
            <form id="pending_form" action="{% url 'managements:pending_result' rent.equip.pk manager %}" method="post" onkeydown="return event.key != 'Enter';" enctype="multipart/form-data">
                                                        <!-- 바코드 스캔 시 자동으로 제출되는 것 방지-->
                {% csrf_token %}
                    <input style='opacity:0; cursor:default;' name="beforeAmt" id="beforeAmt" value="" onkeyup="eventKeyup(this.value)"/>
                    <table class="info_table">
                        <tr>
                            <td>대여자 학번 : </td>
                            <td>{{ rent.student.student_id }}</td>
                            {% comment %} <td><input type="text" name="student" value="{{ rent.student.name }}"></td> {% endcomment %}
                        </tr>
                        <tr>
                            <td>대여 물품 번호 : </td>
                            <td>{{ rent.equip.equip_id }}</td>
                            {% comment %} <td><input type="text" name="equip" value="{{ rent.equip.equip_id }}"></td> {% endcomment %}
                        </tr>
                        <tr>
                            <td>반납 보류 사유: </td>
                            <td>
                                <input type="text" name="reason" class="form-control" placeholder="보류 사유를 작성하세요.">
                            </td>
                        </tr>
                        <tr style="color:#aaaaaa; ">
                            <td>이미지 첨부 (선택) : </td>
                            <td>
                                <input type="file" name="file" id="file" multiple="multiple"/>
                            </td>
                        </tr>
                    </table>
                    <input type="submit" value="보류" class='submit_btn' onclick="location.href='{% url 'managements:pending_result' rent.equip.pk manager %}'; alert('반납이 보류되었습니다.')" /> 
            </form>
        </div>
    </div>
</div>
{%endblock%}

managements/templates/managements/rent.html
{% extends 'base.html' %}
{% load static %}

{% block custom_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javaScript">
        function eventKeyup(str){
            let str2 = str.slice(3, 10)
            $("#id_student_id").val(str2);    // jQuery 이용
        }
        $(function(){
            $("input[name=cur_focus]").click(function(){
                alert('학생증 QR 코드를 스캔해주세요.');
                $("input[name=beforeAmt]").focus();
                $('input[id=id_student_id]').css('background-color', 'rgba(0, 100, 214, 0.25)');
            });
            $("input[name=cur_focus2]").click(function(){
                alert('기자재 바코드를 스캔해주세요.')
                $("input[name=equip_id]").focus();
                $('input[id=id_equip_id]').css('background-color', 'rgba(0, 100, 214, 0.25)');
            });
            $("input[name=lookup]").click(function(){
                alert('학생 정보를 조회합니다.');
                var input_student = $('#id_student_id').val();
                $.ajax({
                    url:'search/',
                    data:{'input_student':input_student},
                    success:function(data){
                        $('#lookup').html(data)
                    }
                })

            });
        });

        // 대여 중복 검사
        function id_overlap_check(e) {
            if ($('#id_student_id').val() == '') {
                alert('학생 번호를 입력해주세요.');
                event.preventDefault()
                return false;
            }
            else if ($('#id_equip_id').val() == '') {
                alert('기자재 번호를 입력해주세요.');
                console.log($("#file").val())
                event.preventDefault()
                return false;
            }
            else if ($("#file").val() == '') {
                alert('기자재 상태 확인을 위한 사진을 등록해주세요.');
                event.preventDefault();
                return false;
            }
            else if($("#id_manager").val() == ''){
                alert('검사자 이름을 입력해주세요.')
                event.preventDefault()
                return false;
            }

            id_overlap_input = document.querySelector('input[name="equip_id"]');
            id_overlap_input_st = document.querySelector('input[name="student_id"]');
        
            $.ajax({
                url: "{% url 'managements:rent_overlap_check' %}",
                data: {
                    'equip_id': id_overlap_input.value,
                    'student_id': id_overlap_input_st.value
                },
                datatype: 'json',
                success: function (data) {
                    console.log(id_overlap_input.value)
                    console.log(id_overlap_input_st.value)
                    if (data['s_exist'] == 'fail') {
                        alert('등록되지 않은 학생입니다.')
                    } 
                    if (data['e_exist'] == 'fail') {
                        alert('등록되지 않은 기자재입니다.')
                    }

                    if (data['overlap'] == 'e_fail') {
                        alert('이미 대여중인 기자재입니다.');
                    } else if (data['overlap']== 's_fail') {
                        
                    } else if (data['overlap']== 'pass') {
                        alert('대여가 완료되었습니다.');
                        $('form').submit()
                    }
                }
            })
        }
    </script>

{% endblock custom_script %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'managements/rent_page.css' %}">
{% endblock custom_css %}

{%block content%}
<div class="container">
    <div class="row">
        <div class="subtitle" style="margin-top: 50px; text-align: center;">
            <h1 style='font-weight:bold; '>대여 정보 입력</h1>
        </div>
    </div>
    <div class="row">
        <div class="rentform ">
            <form id="rent_form" action="" method="post" onkeydown="return event.key != 'Enter';" enctype="multipart/form-data">
                                                        <!-- 바코드 스캔 시 자동으로 제출되는 것 방지-->
                {% csrf_token %}
                    <input style='opacity:0; cursor:default;' name="beforeAmt" id="beforeAmt" value="" onkeyup="eventKeyup(this.value)"/>
                    <table class="info_table" style="text-align:left;">
                        <tr>
                            <td>학번 : </td>
                            <td><input type="text" name='student_id' id='id_student_id' ></td>
                            <td id='scan_td'>
                                <input type='button' name='cur_focus' value='학생증 스캔' class='scan_btn' id='scan_btn'>
                                <input type='button' name='lookup' value='학생 조회' class='lookup_btn' id='lookup_btn'> 
                            </td>
                        </tr>
                        <tr>
                            <td>물품 번호 : </td>
                            <td><input type="text" name='equip_id' id='id_equip_id' ></td>
                            <td id='scan_td'><input type="button" name='cur_focus2' value='기자재 스캔' class='scan_btn'></td>
                        </tr>
                        <tr>
                            <td>물품 태그 부착 여부 : </td>
                            <td>
                                <select name="tag_attach" id="id_tag_attach">
                                    <option value=True>부착</option>
                                    <option value=False>미부착</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>기기작동 여부 : </td>
                            <td>
                                <select name="equip_work" id = "id_equip_work">
                                    <option value=True>작동</option>
                                    <option value=False>미작동</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>마우스 및 충전기 지급 여부 : </td>
                            <td>
                                <select name="accessories" id = "id_accessories">
                                    <option value=None>-</option>
                                    <option value=False>미지급</option>
                                    <option value=True>지급</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>물품 사진: </td>
                            <td>
                                <input type="file" name="file" id="file" multiple="multiple" class="form-control">
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>검사자 이름 : </td>
                            <td><input type="text" name='manager' id = "id_manager"></td>
                        </tr>
                    </table>
                    <input type="button" value="대여" class='submit_btn' onclick='id_overlap_check()' /> 
            </form>
        </div>
    </div>

    <div id = "lookup" style="margin:auto; text-align:center; font-size:20px;color:red"></div>
</div>
{%endblock%}

managements/templates/managements/return_info.html
{% extends 'base.html' %}
{% load static %}

{% block custom_script %}
<script>
    function id_overlap_check(e) {
        let id_overlap_input = '{{equip.equip_id}}'
            $.ajax({
                url: "{% url 'managements:pending_overlap_check' %}",
                data: {
                    'equip_id':id_overlap_input
                },
                datatype: 'json',
                success: function (data) {
                    if (data['overlap'] == 'fail') {
                        alert('이미 보류 상태인 기자재입니다.');
                        event.preventDefault()
                        return false;
                    } else {
                        alert('보류 사유를 입력해주세요.');
                    }
                }
            })
        }
</script>
{% endblock custom_script %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'managements/manage_list.css' %}">
    <link rel="stylesheet" href="{% static 'managements/return_page.css' %}">
{% endblock custom_css %}

{%block content%}
    <div class="subtitle" style="margin-top: 50px; text-align: center;">
        <h1 style='font-weight:bold; '>조회된 반납 가능한 정보</h1>
    </div>
    <div class="container">
        <table class='table table-striped rent_list_table'>
            <thead>
                <tr>
                    <td><b>학번</b></td>
                    <td><b>이름</b></td>
                    <td><b>학적 상태</b></td>
                    <td><b>물품번호</b></td>
                    <td><b>물품종류</b></td>
                    <td><b>물품태그</b></td>
                    <td><b>기기작동</b></td>
                    <td><b>악세서리</b></td>
                    <td><b>대여 상태</b></td>
                    <td><b>대여일</b></td>
                    <td><b>검사자</b></td>
                    <td><b>서약서</b></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{student.student_id}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.status}}</td>
                    <td>{{equip.equip_id}}</td>
                    <td>{{equip.get_equip_type_display}}</td>
                    <td>
                        {% if rent.tag_attach%}
                            <span style="color:green; text-align:center">O</span>
                        {% else%}    
                            <span style="color:red; text-align:center">X</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if rent.equip_work%}
                            <span style="color:green; text-align:center">O</span>
                        {% else%}    
                            <span style="color:red; text-align:center">X</span>
                        {% endif %}
                    </td>
                    {% if rent.accessories%}
                        <td>지급</td>
                    {%elif rent.accessories is None%}
                        <td>-</td>
                    {% else%}    
                        <td>미지급</td>
                    {% endif %}
                    {% if rent.equip.rent_status == 'pending' %}
                        <td id='rent_pending'>반납 보류</td>
                    {% elif rent.equip.rent_status == 'impossible' %}    
                        <td id='rent_impossible'>대여중</td>
                    {% endif %}
                    <td>{{rent.rent_date | date:'Y-m-d'}}</td>
                    <td>{{rent.manager}}</td>
                    <td>
                        {% if rent.active %}
                            <span style="color:green; text-align:center">O</span>
                        {% else %}
                            <span style="color:red; text-align:center">X</span>
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
        <div style='text-align:center;'>
            {% for image in rent_images %}
                <img src="{{ image.equip_pic.url }}" class='rent_equip_img'> <br>
            {% endfor %}
        </div>
        <div style='text-align:center; margin:30px 0'>
            <input type="button" class="submit_btn" value="반납" onclick="location.href='{% url 'managements:return_result' equip.pk manager%}'; alert('반납이 완료되었습니다.')">
            <input type="button" class="submit_btn" value="보류" onclick="id_overlap_check(); location.href='{% url 'managements:pending' equip.pk manager%}';">
        </div>
    </div>
{%endblock content%}